const mockPosts = [
  {
    id: "post-1",
    title: "The future of technology is changing faster than ever",
    subreddit: "technology",
    author: "techfan",
    score: 1248,
    num_comments: 184,
    selftext:
      "A discussion about the latest developments in technology and how they may affect everyday life.",
    thumbnail: null,
    url: "https://example.com",
  },
  {
    id: "post-2",
    title: "What is everyone learning right now?",
    subreddit: "learnprogramming",
    author: "codelearner",
    score: 876,
    num_comments: 92,
    selftext:
      "A community discussion about programming languages, frameworks and useful development skills.",
    thumbnail: null,
    url: "https://example.com",
  },
  {
    id: "post-3",
    title: "Share your favourite project ideas",
    subreddit: "webdev",
    author: "frontenddev",
    score: 642,
    num_comments: 67,
    selftext:
      "A collection of interesting web development projects and ideas for developers to try.",
    thumbnail: null,
    url: "https://example.com",
  },
  {
    id: "post-4",
    title: "Show us what you have been building",
    subreddit: "programming",
    author: "developer",
    score: 521,
    num_comments: 43,
    selftext:
      "Developers share personal projects, experiments and applications they have been working on.",
    thumbnail: null,
    url: "https://example.com",
  },
  {
    id: "post-5",
    title: "The best productivity tips for developers",
    subreddit: "productivity",
    author: "productivecoder",
    score: 394,
    num_comments: 31,
    selftext:
      "A discussion about tools and habits that can make software development more productive.",
    thumbnail: null,
    url: "https://example.com",
  },
  {
    id: "post-6",
    title: "The biggest stories everyone is talking about today",
    subreddit: "news",
    author: "dailynews",
    score: 1102,
    num_comments: 156,
    selftext:
      "A roundup of current events and important stories generating discussion today.",
    thumbnail: null,
    url: "https://example.com",
  },
  {
    id: "post-7",
    title: "What games are you playing this weekend?",
    subreddit: "gaming",
    author: "gamer42",
    score: 934,
    num_comments: 128,
    selftext:
      "A community discussion about favourite games, new releases and weekend gaming plans.",
    thumbnail: null,
    url: "https://example.com",
  },
  {
    id: "post-8",
    title: "Your favourite sports moment of the year",
    subreddit: "sports",
    author: "sportsfan",
    score: 785,
    num_comments: 89,
    selftext:
      "Share the sporting moments that have stood out to you this year.",
    thumbnail: null,
    url: "https://example.com",
  },
  {
    id: "post-9",
    title: "The latest developments in consumer technology",
    subreddit: "technology",
    author: "techreader",
    score: 713,
    num_comments: 74,
    selftext:
      "A discussion about new devices, software and trends in consumer technology.",
    thumbnail: null,
    url: "https://example.com",
  },
  {
    id: "post-10",
    title: "Which game deserves more attention?",
    subreddit: "gaming",
    author: "indiegamer",
    score: 598,
    num_comments: 61,
    selftext:
      "A discussion about underrated games that deserve a bigger audience.",
    thumbnail: null,
    url: "https://example.com",
  },
  {
    id: "post-11",
    title: "What game has kept you playing the longest?",
    subreddit: "gaming",
    author: "gameplayer",
    score: 734,
    num_comments: 118,
    selftext:
      "What game have you spent the most time playing, and what keeps bringing you back to it?",
    thumbnail: null,
    url: "https://example.com",
  },
  {
    id: "post-12",
    title: "What small programming habit improved your workflow?",
    subreddit: "programming",
    author: "codebuilder",
    score: 589,
    num_comments: 76,
    selftext:
      "Share a small programming habit, shortcut or workflow improvement that made a noticeable difference.",
    thumbnail: null,
    url: "https://example.com",
  },
  {
    id: "post-13",
    title: "Show us your favourite web development tools",
    subreddit: "webdev",
    author: "webbuilder",
    score: 463,
    num_comments: 54,
    selftext:
      "What tools, extensions or services do you use most often when building websites?",
    thumbnail: null,
    url: "https://example.com",
  },
  {
    id: "post-14",
    title: "What technology are you most excited about?",
    subreddit: "technology",
    author: "futurethinker",
    score: 921,
    num_comments: 143,
    selftext:
      "There are always new technologies appearing. Which one do you think will have the biggest impact?",
    thumbnail: null,
    url: "https://example.com",
  },
  {
    id: "post-15",
    title: "How do you stay productive while working from home?",
    subreddit: "productivity",
    author: "focusedworker",
    score: 347,
    num_comments: 39,
    selftext:
      "Share your routines, tools and habits for staying focused and productive while working remotely.",
    thumbnail: null,
    url: "https://example.com",
  },
];

export default mockPosts;
